from django.db import models
from django.contrib.auth import get_user_model

# Create your models here.
"""
class Post:
    id int
    title str(50)
    content text
    created datetime
"""

User = get_user_model()

class Post(models.Model):
    #id is generated by django
    title = models.CharField(max_length=50)
    content = models.TextField(max_length=500)
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="posts")


    def __str__(self):
        return self.title
